# Deploy static content to GitHub Pages
name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  push:
    branches:
      - main  # Adjust branch name if needed
  workflow_dispatch:

# Jobs to be executed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build static content
      - name: Build
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjust this path based on your build output

      # Define the URL output
      - name: Set URL output
        id: deployment
        run: echo "::set-output name=page_url::https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}/"
